### PR TITLE
Feat/add product tab

### PR DESCRIPTION
**Pull request by shuvo-me**
https://www.loom.com/share/77f9d2a30ab4495284556ca225747b55

### CODE REVIEW

**Review by devzakir — CHANGES_REQUESTED** [review]
For now, Please keep the premium product as it was earlier. 

- [ ] Add a new section for free products after "Why Should You Buy Our Product?"

**Comment by shuvo-me** [comment]
> For now, Please keep the premium product as it was earlier.
> 
> * [ ]  Add a new section for free products after "Why Should You Buy Our Product?"

image
added free product section with view all button

**Comment by Rakib0101** [comment]
@shuvo-me vai, I suggest adding a background or border to the free product section and its preceding section. This will help differentiate between the two sections more clearly, making it easier to understand. @devzakir vai other things are okay from my side

**Comment by shuvo-me** [comment]
@devzakir  
https://www.loom.com/share/6f78db4c71eb494a9cf7d8fd97d53f3e

**Review by devzakir — APPROVED** [review]

**Pull request merged**
