### PR TITLE
Make new landing page

### PR DESCRIPTION
**Pull request by shuvo-me**
https://www.loom.com/share/fb1b582cdc4e4904b3fed10077d1179c

### CODE REVIEW

**Review by devzakir — CHANGES_REQUESTED** [review]
@shuvo-me there will be a new page `custom-web-development`

**Comment by shuvo-me** [comment]
> @shuvo-me there will be a new page `custom-web-development`

can not understand what you are talking about. please clarify

**Comment by shuvo-me** [comment]
@devzakir https://www.loom.com/share/8623eae59d8247d4b866016ad6878529

**Review by devzakir — CHANGES_REQUESTED** [review]
@shuvo-me the new page route sould be `custom-website-development`

**Pull request closed without merging**
