### PR TITLE
Feat/sync product price with envato

### PR DESCRIPTION
**Pull request by shuvo-me**
https://www.loom.com/share/312b064cec55476cb936b4bc6b1db211

### CODE REVIEW

**Comment by devzakir** [comment]
@shuvo-me bhai, can we remove `.00` from `$149.00`

**Comment by Rakib0101** [comment]
@shuvo-me I couldn't see the preview maybe for env file missing, could you add the .env.example file in GitHub and push again for a preview ?

**Comment by devzakir** [comment]
@shuvo-me Please update

**Comment by shuvo-me** [comment]
> @shuvo-me Please update

@devzakir https://www.loom.com/share/e8d1ee08d01b4e829df54d241b0f1432

**Review by devzakir — APPROVED** [review]

**Pull request merged**
