### PR TITLE
Rakib/responsive issues

### PR DESCRIPTION
**Pull request by Rakib0101**
@devzakir vai, responsive issues fixed as you instructions

here is [loom](https://www.loom.com/share/b7444d1311f34b4f9ebcad5e93c99aa3)

### CODE REVIEW

**Comment by devzakir** [comment]
@Rakib0101 vercel deploy failed.

**Comment by Rakib0101** [comment]
@devzakir when I created PR, I also mentioned that, please give me details, where it's found error.

Screenshot at Dec 05 15-57-38

**Comment by devzakir** [comment]
@Rakib0101 I am so sorry bhai, I am sending you details right now

**Comment by Rakib0101** [comment]
@devzakir deployment issues are fixed vai, you can check now

**Pull request merged**
