### PR TITLE
Add canonical link for seo

### PR DESCRIPTION
**Pull request by shuvo-me**

### CODE REVIEW

**Comment by devzakir** [comment]
@shuvo-me please add description or loom, where you fix and how you fixed.

**Comment by shuvo-me** [comment]
> fixed

https://www.loom.com/share/4f53df15ff0a4c6eb6977bdd744c12e5

**Comment by devzakir** [comment]
@shuvo-me blog details e page laghbe na canonical tag?

**Comment by shuvo-me** [comment]
> @shuvo-me blog details e page laghbe na canonical tag?
@devzakir added canonical tag in blog details page

**Pull request merged**
